source_list:
  - CP

target_list:
  - REGIS_DIM

staging_dir: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data
      filename: receipts_delta_GBR_14_10_2017.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address
    app_package: spark.mongodb.input.uri

CP:
  s3_conf:
    s3_bucket: raj-4321
    filename: KC_Extract_1_20171009.csv

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  source_data: CP
  loadingQuery: >
    SELECT
      MONOTONICALLY_INCREASING_ID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
      FROM
        CP
      WHERE
        INS_DT = CURRENT_DATE
      ) CP

s3_conf:
  s3_bucket: raj-4321



redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT



